deepspeed --include=localhost:0,1,2,3,4,5,6,7 gllava/train/train.py \
                                            --mm_projector_lr 3e-5 \
                                            --visual_merge_lr 1e-6 \
                                            --deepspeed ./scripts/zero3.json \
                                            --model_name_or_path ./checkpoints_sve/Qwen2.5_geo170k_with_alignment \
                                            --version qwen_2 \
                                            --data_path ./playground/data/Geo170K/qa_tuning.json \
                                            --image_folder ./playground/data/Geo170K/images \
                                            --vision_tower openai/clip-vit-large-patch14-336 \
                                            --mm_projector_type mlp2x_gelu \
                                            --mm_vision_select_layer -2 \
                                            --mm_use_im_start_end False \
                                            --mm_use_im_patch_token False \
                                            --image_aspect_ratio pad \
                                            --group_by_modality_length True \
                                            --bf16 True \
                                            --output_dir ./checkpoints_sve/SVE-Math-7B \
                                            --num_train_epochs 2 \
                                            --per_device_train_batch_size 6 \
                                            --per_device_eval_batch_size 4 \
                                            --gradient_accumulation_steps 1 \
                                            --evaluation_strategy "no" \
                                            --save_strategy "steps" \
                                            --save_steps 50000 \
                                            --save_total_limit 1 \
                                            --learning_rate 3e-5 \
                                            --weight_decay 0. \
                                            --warmup_ratio 0.03 \
                                            --lr_scheduler_type "cosine" \
                                            --logging_steps 1 \
                                            --tf32 True \
                                            --model_max_length 32768 \
                                            --gradient_checkpointing True \
                                            --dataloader_num_workers 4 \
                                            --lazy_preprocess True \
                                            --num_of_kvs 4 \
                                            --merge_version identify_channel \
                                            --use_img_aug \
                                            --white_bg \
                                            --translation_ratio 0.25
